name: env_tutorial
## Triggers the workflow on when there is a push, or 
## pull request on the main branch
on: [pull_request, push] 

env:
  ## Sets environment variable
  API_KEY: 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  